kind: pipeline
type: docker
name: Build-Spark

steps:
- name: Go-Build-WEB
  image: node:18.19.0-bullseye
  commands:
  - cd web
  - npm install
  - npm run build-prod

- name: Go-Build-WEB-V2
  image: golang:latest
  commands:
  - go install github.com/rakyll/statik
  - statik -m -src="./web/dist" -f -dest="./server/embed" -p web -ns web

- name: Go-Build-Client
  image: golang:latest
  commands:
  - mkdir ./built
  - go mod tidy
  - go mod download
  - bash ./scripts/build.client.sh

- name: Go-Build-Server
  image: golang:latest
  commands:
  - mkdir ./releases
  - bash ./scripts/build.server.sh
